pizzas/urls.py
""""Схемы URL для Pizzas"""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех пицц
    path('pizzas/', views.pizzas, name='pizzas'),
    # Страница с топпингами
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    # Страница для добавления новой пиццы
    path('new_pizza/', views.new_pizza, name='new_pizza'),
    # Страница для редактирования топпинга
    path('edit_topping/<int:topping_id>/', views.edit_topping, name='edit_topping'),
    # Страница для добалвнеия топпинга к пицце
    path('new_topping/<int:pizza_id>/', views.new_topping, name='new_topping')
    ]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # URL по умолчанию
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name='register'),
]

pizzas/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    """"Пицца, созданная пользователем"""
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        """"Возвращает строковое представление модели"""
        return self.name

class Topping(models.Model):
    """"Топпинги для конкретной пиццы"""
    pizza = models.ForeignKey(Pizza, on_delete=CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """"Возвращает строковое представление модели"""
        return self.name

users/models.py
from django.db import models

# Create your models here.

pizzas/forms.py
from django import forms
from django import forms
from django.forms import widgets
from .models import Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name': ''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name': 'Topping:'}
        widgets = {'name': forms.Textarea(attrs={'cols': 30})}

pizzas/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Pizza, Topping
from .forms import PizzaForm, ToppingForm

# Create your views here.

def index(request):
    """"Домашняя страница приложения Pizzeria"""
    return render(request, 'pizzas/index.html')

@login_required
def pizzas(request):
    """"Выводит список пицц"""
    pizzas = Pizza.objects.filter(owner=request.user).order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

@login_required
def pizza(request, pizza_id):
    """"Выводит одну пиццу и все её топпинги"""
    pizza = Pizza.objects.get(id=pizza_id)
    if pizza.owner != request.user:
        raise Http404

    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

@login_required
def new_pizza(request):
    """"Определяет новый топпинг"""
    if request.method != 'POST':
        form = PizzaForm()
    else:
        """"Обрабатываем данные POST"""
        form = PizzaForm(request.POST)
        if form.is_valid():
            new_pizza = form.save(commit=False)
            new_pizza.owner = request.user
            new_pizza.save()
            return redirect('pizzas:pizzas')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'pizzas/new_pizza.html', context)

@login_required
def new_topping(request, pizza_id):
    """"Добавляет новый топпинг"""
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = ToppingForm()
    else:
        """"Обрабатываем данные POST"""
        form = ToppingForm(request.POST)
        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)

    # Вывести пустую или недействительную форму
    context = {'pizza': pizza, 'form': form}
    return render(request, 'pizzas/new_topping.html', context)

@login_required
def edit_topping(request, topping_id):
    """"Редактирует топпинг"""
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza
    if pizza.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = ToppingForm(instance=topping)
    else:
        form = ToppingForm(request.POST, instance=topping)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza', pizza_id=pizza.id)

    context = {'topping': topping, 'pizza': pizza, 'form': form}
    return render(request, 'pizzas/edit_topping.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """"Регистрация нового пользователя"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('pizzas:index')

    context = {'form': form}
    return render(request, 'registration/register.html', context)

pizzas/templates/pizzas/base.html
{% load bootstrap5 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    </head>
    <body>

      <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'pizzas:index'%}">
            Pizzeria</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'pizzas:pizzas'%}">
                  Pizzas</a></li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
            <span class="navbar-text"}">Hello, {{ user.username }}.</span>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
          {% block page_header %}{% endblock page_header %}
        </div>
        <div>
          {% block content %}{% endblock content %}
        </div>
      </main>

    </body>
</html>

pizzas/templates/pizzas/edit_topping.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Edit topping:</p>

<form action="{% url 'pizzas:edit_topping' topping.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="sumbit">save changes</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-3">Track your pizzas.</h1>

    <p class="lead">There is you can save your pizzas and add toppings for it!</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
      role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

pizzas/templates/pizzas/new_pizza.html
{% extends 'pizzas/base.html' %}
{% load bootstrap5 %}

{% block content %}

<p>Add a new pizza:</p>

<form action="{% url 'pizzas:new_pizza' %}" method='post' class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">add pizza</button>
    {% endbuttons %}
</form>

{% endblock content %}

pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}
{% load bootstrap5 %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p>Add a new topping:</p>
<form action="{% url 'pizzas:new_topping' pizza.id %}" method="post" class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">add topping</button>
    {% endbuttons %}
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
  <h3>{{ pizza }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'pizzas:new_topping' pizza.id %}">add new topping</a>
  </p>

  <ul>
  {% for topping in toppings %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ topping.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'pizzas:edit_topping' topping.id %}">
          edit topping</a></small>
        </h4>
        <div class="card-body">
          {{ topping.name|linebreaks }}
        </div>
    </div>
  {% empty %}
    <p>There are no toppings for this pizza yet.</p>
  {% endfor %}
  </ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block page_header %}
  <h1>Pizzas</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for pizza in pizzas %}
      <li><h3>
          <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No pizzas have been added yet.</h3>></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'pizzas:new_pizza' %}">Add new pizza:</a></h3>

{% endblock content %}